services:
  - type: web
    name: sahay-disaster-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        value: sahay1382@gmail.com
      - key: EMAIL_PASS
        value: mnlewwaagoxfnibx
      - key: CLOUDINARY_CLOUD_NAME
        value: qnkopie9
      - key: CLOUDINARY_API_KEY
        value: 166159337622438
      - key: CLOUDINARY_API_SECRET
        value: xB6brChZUAF4UAQM5ah4eiSq-OA
      - key: CLOUDINARY_URL
        value: cloudinary://166159337622438:xB6brChZUAF4UAQM5ah4eiSq-OA@qnkopie9
